name       : python-gmpy2
version    : 2.0.8
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/g/gmpy2/gmpy2-2.0.8.zip : dd233e3288b90f21b0bb384bcc7a7e73557bb112ccf0032ad52aa614eb373d3f
homepage   : https://github.com/aleaxit/gmpy
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Provides C-coded Python modules for fast multiple-precision arithmetic
description: |
    gmpy2 is a C-coded Python extension module that supports multiple-precision arithmetic. gmpy2 is the successor to the original gmpy module. The gmpy module only supported the GMP multiple-precision library. gmpy2 adds support for the MPFR (correctly rounded real floating-point arithmetic) and MPC (correctly rounded complex floating-point arithmetic) libraries. gmpy2 also updates the API and naming conventions to be more consistent and support the additional functionality.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
